name: Build Docker for ROLLING

on:
  schedule:
    - cron: '30 2 * * *'  
  push:
    paths:
      - 'rolling/**'
    branches: [ "master" ]
  pull_request:
    paths:
      - 'rolling/**'
    branches: [ "master" ]

jobs:
  push_to_registry:
    name: push docker image to hub
    runs-on: ubuntu-latest
    steps:
      - name: check repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and push multi-platform ROLLING
        uses: docker/build-push-action@v5
        with:
          context: ./rolling/
          push: true
          tags: |
            pokys/xojowebapp:rolling
          platforms: linux/amd64,linux/arm64,linux/386,linux/arm/v7
